# Generated by Django 5.0.7 on 2024-08-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=200)),
                ('taskDescription', models.CharField(max_length=500)),
                ('taskDueDate', models.DateField()),
                ('selectedCategory', models.CharField(max_length=50)),
                ('selectedPrio', models.CharField(max_length=50)),
                ('subtasks', models.JSONField(blank=True, default=list)),
                ('selectedContacts', models.JSONField(blank=True, default=list)),
                ('currentState', models.CharField(max_length=100)),
            ],
        ),
    ]
