# Generated by Django 5.0.7 on 2024-08-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_taskitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskitem',
            old_name='selectedPrio',
            new_name='prio',
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='currentState',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='selectedContacts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='subtasks',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='taskDescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
