# Generated by Django 5.0.7 on 2024-08-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_selectedprio_taskitem_prio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='user',
        ),
    ]
