# Generated by Django 5.0.7 on 2024-08-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_contactitem_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactitem',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactitem',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactitem',
            name='nr',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=100),
        ),
    ]
