# Generated by Django 5.0.7 on 2024-08-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_contactitem_color_alter_contactitem_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactitem',
            name='nr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True),
        ),
    ]
