# Generated by Django 5.0.7 on 2024-08-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_taskitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactitem',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
    ]
